### PR TITLE
1. fix text error for certificate

### PR DESCRIPTION
**Pull request by ssignik**
fix text error for certificate

### CODE REVIEW

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Review by LiYanghang00 — APPROVED** [review]
无问题

**Comment by shishupei** [comment]
<table style="border-collapse: collapse" border=1>
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>Check代码检查</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/certification-server/4/4_Check代码检查.html">查看日志</a></td>
</tr>

<tr>
    <td>DT覆盖率</td>
    <td>7.3953%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/certification-server/4/4_测试覆盖率.html">查看日志</a></td>
</tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/certification-server/4/4_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>漏洞扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/certification-server/4/4_漏洞扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/certification-server/4/4_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>TestPlan接口测试</td>
    <td>&#9989;</td>
    <td></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/128c1a12cee14cd3ae4059676f9c3c61/08d19b446a014314b320bec196eb9b94">点击跳转</a></td>
</tr>
</table>

**Review by shishupei — APPROVED** [review]
11111

**Pull request merged**
